# Generated by Django 2.1.3 on 2019-01-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('phone', models.CharField(default='1', max_length=255)),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='BioDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('inputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=1)),
                ('saleNum', models.IntegerField(default=1)),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间')),
                ('bookCover', models.ImageField(default='', height_field='url_height', upload_to='img', width_field='url_width')),
                ('fileMore', models.FileField(default='', upload_to='files')),
                ('author', models.ManyToManyField(related_name='book_author', to='proApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Catinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('nameinfo', models.CharField(max_length=1000)),
                ('feature', models.CharField(max_length=1000)),
                ('livemethod', models.CharField(max_length=1000)),
                ('feednn', models.CharField(max_length=1000)),
                ('feedmethod', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('n_comments', models.IntegerField()),
                ('n_pingbacks', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('authors', models.ManyToManyField(to='proApp.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proApp.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '人员管理',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proApp.Publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='author_book', to='proApp.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proApp.Department'),
        ),
    ]
