# Generated by Django 2.1.3 on 2019-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0002_auto_20190108_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(default='img/default.png', upload_to='img'),
        ),
    ]
