# Generated by Django 2.1.3 on 2019-01-09 14:37

from django.db import migrations, models
import proApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0003_auto_20190109_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(default='img/default.png', upload_to=proApp.models.bookCoverPath),
        ),
    ]
