# Generated by Django 2.1.3 on 2019-01-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0005_auto_20190114_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='headImg',
            field=models.ImageField(default='', upload_to='icons'),
        ),
    ]
