# Generated by Django 2.1.3 on 2019-01-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0006_author_headimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='headImg',
            new_name='head_img',
        ),
    ]
