# Generated by Django 2.1.3 on 2019-01-14 15:22

from django.db import migrations, models
import proApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0008_auto_20190114_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='head_img',
            field=models.ImageField(default='', upload_to=proApp.models.headimgPath),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(upload_to=proApp.models.bookCoverPath),
        ),
    ]
